
version: "3"
services:
  database:
    image: postgres:13-alpine
    env_file:
      - ./config/.env.local
    ports:
      - 5432:5432
    volumes:
      - flick-db-data:/var/lib/postgresql/data/
      
volumes:
  flick-db-data: